Feature/5 1 open thread
sw21-tug/Team_09 pull request #66
Opened 2021-06-01 22:06 UTC by PatrickStru

2021-06-02 09:48 UTC, alexander-toch requested changes

2021-06-02 09:48 UTC, alexander-toch commented on app/src/main/java/com/tugraz/asd/modernnewsgroupapp/FragmentOpenThread.kt
> +        getThreadMessages(controller)
the parameter is not needed here, as you can access controller in the whole class

2021-06-02 09:48 UTC, alexander-toch commented on app/src/main/java/com/tugraz/asd/modernnewsgroupapp/FragmentOpenReplyThread.kt
> +        getReplyThreadMessage(controller)
param is always controller. You can skip it here and just use controller inside `getReplyThreadMessage`

2021-06-02 09:48 UTC, alexander-toch commented on app/src/main/java/com/tugraz/asd/modernnewsgroupapp/FragmentOpenReplyThread.kt
> +        val thread = Thread {
use coroutines instead of thread.start and .join (see lifecycleScope.launch in other fragments)

2021-06-02 09:48 UTC, alexander-toch commented on app/src/main/java/com/tugraz/asd/modernnewsgroupapp/FragmentOpenThread.kt
> +            thread.start()
use coroutines instead of thread .join (which would block the UI)

2021-06-07 06:56 UTC, PatrickStru commented on app/src/main/java/com/tugraz/asd/modernnewsgroupapp/FragmentOpenThread.kt
> +            thread.start()
Very unstable with the current code base. Adapt thread safe calls in own task

2021-06-07 06:56 UTC, PatrickStru commented on app/src/main/java/com/tugraz/asd/modernnewsgroupapp/FragmentOpenReplyThread.kt
> +        val thread = Thread {
Very unstable with the current code base. Adapt thread safe calls in own task

2021-06-09 06:14 UTC, alexander-toch approved these changes

2021-06-09 06:15 UTC, merged